language: node_js

# versions for deploying
node_js:
 - '10.0'
 - '9.0'

 # travis caching
cache:
  directories:
    - node_modules

install:
  npm install

# script to run
script:
  npm run test

# code coverage
after_success:
  npm run cover

# toggle branch
branches:
  only:
    - master