language: node_js

# versions for deploying
node_js:
 - '10.0'
 - '9.0'

 # travis caching
cache:
  directories:
    - node_modules

# dependency installation
install:
  npm install

# script to run
script:
  npm run test

# code coverage
after_success:
  npm run cover

# toggle branch
branches:
  only:
    - master

# notification settings
notifications:
  email:
    recipients:
      - xuwy27@mail2.sysu.edu.cn
      - xiongyq7@mail2.sysu.edu.cn
    on_success: never # default: change
    on_failure: always # default: always